Map carrier codes module with brand
vippsas/vipps-checkout-magento pull request #3
Opened 2023-02-20 08:45 UTC by alexandrosk

2023-02-20 09:09 UTC, Ceredron approved these changes

2023-02-20 09:10 UTC, Ceredron requested changes

2023-02-20 09:10 UTC, Ceredron commented on Controller/Vipps/Logistics.php
> +            $requestData = $this->serializer->unserialize('{"streetAddress":"Sandakerveien 6314","postalCode":"0483","region":"OSLO","country":"NO"}');
Todo

2023-02-20 09:15 UTC, alexandrosk commented on Controller/Vipps/Logistics.php
> +            $requestData = $this->serializer->unserialize('{"streetAddress":"Sandakerveien 6314","postalCode":"0483","region":"OSLO","country":"NO"}');
Fixed!

2023-02-28 09:42 UTC, Ceredron approved these changes

2023-02-28 09:53 UTC, merged